import { StyleSheet, Platform } from 'react-native';

export const createCartStyles = (colors) => StyleSheet.create({
    // --- CartButton (Floating Bottom Bar) ---
    floatingButtonContainer: {
        position: 'absolute',
        bottom: 20,
        left: 16,
        right: 16,
        zIndex: 999,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
    },
    floatingButton: {
        backgroundColor: colors.primary,
        borderRadius: 28,
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    floatingButtonLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    badge: {
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        borderRadius: 14,
        minWidth: 28,
        height: 28,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 6,
        marginRight: 10,
    },
    badgeText: {
        color: colors.primaryText,
        fontWeight: 'bold',
        fontSize: 14,
    },
    floatingButtonTitle: {
        color: colors.primaryText,
        fontWeight: 'bold',
        fontSize: 16,
    },
    floatingButtonPrice: {
        color: colors.primaryText,
        fontWeight: 'bold',
        fontSize: 16,
    },

    // --- CartDrawer (Modal / Bottom Sheet) ---
    modalOverlay: {
        flex: 1,
        backgroundColor: colors.modalOverlay,
        justifyContent: 'flex-end',
    },
    drawerContainer: {
        backgroundColor: colors.card,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        maxHeight: '85%',
        minHeight: '40%',
        paddingBottom: Platform.OS === 'ios' ? 34 : 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 10,
    },
    drawerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 14,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
    },
    closeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.disabledBg,
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeButtonText: {
        color: colors.text,
        fontSize: 16,
        fontWeight: 'bold',
    },
    drawerTitleContainer: {
        alignItems: 'center',
        flex: 1,
    },
    drawerTitle: {
        color: colors.text,
        fontSize: 18,
        fontWeight: 'bold',
    },
    drawerSubtitle: {
        color: colors.textSecondary,
        fontSize: 13,
        marginTop: 2,
    },
    clearCartButton: {
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    clearCartText: {
        color: colors.error,
        fontSize: 13,
        fontWeight: '600',
    },
    itemsScroll: {
        paddingHorizontal: 20,
        paddingTop: 10,
    },
    emptyContainer: {
        paddingVertical: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyIcon: {
        fontSize: 48,
        marginBottom: 12,
    },
    emptyText: {
        color: colors.textSecondary,
        fontSize: 16,
        fontWeight: '500',
    },
    drawerFooter: {
        paddingHorizontal: 20,
        paddingTop: 14,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: colors.border,
        backgroundColor: colors.card,
    },
    minOrderWarning: {
        color: colors.error,
        fontSize: 12,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 10,
    },
    checkoutButton: {
        backgroundColor: colors.primary,
        borderRadius: 24,
        height: 52,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    checkoutButtonDisabled: {
        opacity: 0.5,
    },
    checkoutButtonPrice: {
        color: colors.primaryText,
        fontWeight: 'bold',
        fontSize: 16,
    },
    checkoutButtonText: {
        color: colors.primaryText,
        fontWeight: 'bold',
        fontSize: 16,
    },
    checkoutButtonBadge: {
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        borderRadius: 12,
        minWidth: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 6,
    },
    checkoutButtonBadgeText: {
        color: colors.primaryText,
        fontWeight: 'bold',
        fontSize: 12,
    },

    // --- CartItem (Individual Item Row) ---
    itemRow: {
        paddingVertical: 14,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
    },
    itemMain: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    itemInfo: {
        flex: 1,
        marginRight: 12,
    },
    itemName: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '600',
        marginBottom: 4,
    },
    itemNotes: {
        color: colors.textSecondary,
        fontSize: 12,
        fontStyle: 'italic',
        marginTop: 2,
    },
    itemPrice: {
        color: colors.text,
        fontSize: 15,
        fontWeight: 'bold',
        textAlign: 'right',
    },
    itemUnitPrice: {
        color: colors.textSecondary,
        fontSize: 12,
        textAlign: 'right',
        marginTop: 2,
    },
    itemControls: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
    },
    stepper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.disabledBg,
        borderRadius: 16,
        paddingHorizontal: 4,
        paddingVertical: 2,
    },
    stepperButton: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: colors.card,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: colors.border,
    },
    stepperButtonText: {
        color: colors.text,
        fontSize: 16,
        fontWeight: 'bold',
        lineHeight: 18,
    },
    stepperQuantity: {
        color: colors.text,
        fontSize: 14,
        fontWeight: 'bold',
        paddingHorizontal: 12,
    },
    removeButton: {
        marginLeft: 'auto',
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    removeButtonText: {
        color: colors.error,
        fontSize: 12,
        fontWeight: '600',
    },
});
