import { StyleSheet, Platform } from 'react-native';

/**
 * Creates dynamic styles for the Mobile Profile Screen and Auth Gateway based on active theme colors.
 * @param {Object} colors - Active theme color tokens from useTheme().
 * @returns {Object} StyleSheet object.
 */
export const getStyles = (colors) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        scrollContent: {
            paddingHorizontal: 20,
            paddingTop: Platform.OS === 'ios' ? 50 : 30,
            paddingBottom: 40,
        },
        topHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 20,
        },
        headerTitle: {
            fontSize: 26,
            fontWeight: '800',
            color: colors.text,
        },
        themeToggleContainer: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        themeToggleText: {
            marginRight: 8,
            fontSize: 14,
            fontWeight: '600',
            color: colors.text,
        },
        card: {
            backgroundColor: colors.card,
            borderRadius: 16,
            padding: 24,
            borderWidth: 1,
            borderColor: colors.border,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 3,
        },
        cardTitle: {
            fontSize: 22,
            fontWeight: '700',
            textAlign: 'center',
            color: colors.text,
            marginBottom: 20,
        },
        avatarContainer: {
            alignItems: 'center',
            marginBottom: 24,
        },
        avatarTouchable: {
            position: 'relative',
        },
        avatarImage: {
            width: 100,
            height: 100,
            borderRadius: 50,
            borderWidth: 3,
            borderColor: colors.primary,
        },
        avatarPlaceholder: {
            width: 100,
            height: 100,
            borderRadius: 50,
            backgroundColor: colors.inputBg,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: colors.border,
        },
        avatarPlaceholderText: {
            fontSize: 36,
            color: colors.textSecondary,
        },
        uploadBadge: {
            position: 'absolute',
            bottom: 0,
            right: 0,
            backgroundColor: colors.primary,
            width: 32,
            height: 32,
            borderRadius: 16,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: colors.card,
        },
        uploadBadgeText: {
            color: colors.primaryText,
            fontSize: 18,
            fontWeight: 'bold',
            lineHeight: 20,
        },
        formGroup: {
            marginBottom: 16,
        },
        fieldLabel: {
            fontSize: 14,
            fontWeight: '600',
            marginBottom: 6,
            color: colors.text,
        },
        input: {
            height: 48,
            borderWidth: 1,
            borderRadius: 8,
            paddingHorizontal: 14,
            fontSize: 15,
            backgroundColor: colors.inputBg,
            color: colors.inputText,
            borderColor: colors.inputBorder,
        },
        disabledInput: {
            backgroundColor: colors.disabledBg,
            opacity: 0.8,
            color: colors.textSecondary,
        },
        inputError: {
            borderColor: colors.error,
        },
        fieldErrorText: {
            color: colors.error,
            fontSize: 12,
            marginTop: 4,
            fontWeight: '500',
        },
        row: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 16,
        },
        col: {
            flex: 0.48,
        },
        primaryButton: {
            height: 50,
            borderRadius: 25,
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 12,
            backgroundColor: colors.primary,
        },
        primaryButtonText: {
            fontSize: 16,
            fontWeight: '700',
            color: colors.primaryText,
        },
        logoutButton: {
            height: 50,
            borderRadius: 25,
            borderWidth: 1.5,
            borderColor: colors.error,
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 20,
            backgroundColor: 'transparent',
        },
        logoutButtonText: {
            fontSize: 16,
            fontWeight: '700',
            color: colors.error,
        },
        alertBanner: {
            borderWidth: 1,
            borderRadius: 8,
            padding: 12,
            marginBottom: 16,
            alignItems: 'center',
        },
        errorBanner: {
            backgroundColor: colors.errorBg,
            borderColor: colors.error,
        },
        successBanner: {
            backgroundColor: colors.successBg,
            borderColor: colors.success,
        },
        errorText: {
            color: colors.error,
            fontSize: 14,
            fontWeight: '600',
            textAlign: 'center',
        },
        successText: {
            color: colors.success,
            fontSize: 14,
            fontWeight: '600',
            textAlign: 'center',
        },
        loadingContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: colors.background,
        },
        loadingText: {
            marginTop: 12,
            fontSize: 16,
            color: colors.textSecondary,
        },
        authGatewayContent: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingHorizontal: 24,
            paddingBottom: 60,
        },
        authGatewayTitle: {
            fontSize: 36,
            fontWeight: '900',
            color: colors.text,
            letterSpacing: -0.5,
            marginBottom: 8,
        },
        authGatewaySubtitle: {
            fontSize: 16,
            color: colors.textSecondary,
            marginBottom: 40,
            textAlign: 'center',
        },
        gatewayLoginBtn: {
            width: '100%',
            maxWidth: 340,
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: colors.primary,
            shadowColor: colors.primary,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.2,
            shadowRadius: 8,
            elevation: 4,
        },
        gatewayLoginBtnText: {
            fontSize: 16,
            fontWeight: 'bold',
            color: colors.primaryText,
            letterSpacing: 0.5,
        },
        gatewayRegisterText: {
            fontSize: 15,
            color: colors.textSecondary,
            marginTop: 32,
            marginBottom: 16,
        },
        gatewayRegisterBtn: {
            width: '100%',
            maxWidth: 340,
            paddingVertical: 14,
            borderRadius: 12,
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1.5,
            borderColor: colors.primary,
            backgroundColor: 'transparent',
        },
        gatewayRegisterBtnText: {
            fontSize: 16,
            fontWeight: 'bold',
            color: colors.primary,
            letterSpacing: 0.5,
        },
        disabledButton: {
            opacity: 0.6,
        },
        modalOverlay: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: 20,
            backgroundColor: colors.modalOverlay,
        },
        modalCard: {
            width: '85%',
            borderRadius: 16,
            padding: 20,
            alignItems: 'center',
            backgroundColor: colors.card,
        },
        modalTitle: {
            fontSize: 18,
            fontWeight: 'bold',
            marginBottom: 16,
            color: colors.text,
        },
        modalOption: {
            width: '100%',
            paddingVertical: 14,
            borderBottomWidth: 1,
            alignItems: 'center',
            borderBottomColor: colors.border,
        },
        modalOptionText: {
            fontSize: 16,
            fontWeight: '600',
            color: colors.primary,
        },
        modalCancelOption: {
            width: '100%',
            paddingVertical: 14,
            alignItems: 'center',
            marginTop: 4,
        },
        modalCancelText: {
            fontSize: 16,
            fontWeight: '600',
            color: colors.error,
        },
    });
